services:
  # ----------------- ORS application configuration ------------------- #
  ors-app:
    build:
      context: ./
      args:
        OSM_FILE: ./ors-docker/cataluna-latest.osm.pbf
    container_name: ors-app
    ports:
      - "8080:8082"
      - "9001:9001"
    image: openrouteservice/openrouteservice:v9.1.1
    volumes:
      - ./ors-docker:/home/ors
    environment:
      REBUILD_GRAPHS: False
      CONTAINER_LOG_LEVEL: INFO
      XMS: 1g
      XMX: 2g
      ADDITIONAL_JAVA_OPTS: ""
    networks:
      ors-network:
        ipv4_address: 172.28.0.2

  # ----------------- VROOM service configuration ------------------- #
  vroom:
    image: vroomvrp/vroom-docker:v1.11.0
    container_name: vroom
    ports:
      - "3000:3000"
    volumes:
      - ./vroom-conf/:/conf
    environment:
      - VROOM_ROUTER=ors  # router to use, osrm, valhalla or ors
    depends_on:
      - ors-app
    networks:
      ors-network:
        ipv4_address: 172.28.0.3

  # --------------- SQL Server --------------------------------------- #
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    hostname: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "PlusTrack123456!"
      MSSQL_PID: "Evaluation"
    restart: unless-stopped

# ----------------- Shared Network ------------------- #
networks:
  ors-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
