// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlusTrack.API.Domain.AbstractRepositories;

#nullable disable

namespace PlusTrack.API.Migrations
{
    [DbContext(typeof(PlusTrackDbContext))]
    partial class PlusTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LicenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId")
                        .IsUnique()
                        .HasFilter("[LicenseId] IS NOT NULL");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surnames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeopleAmount")
                        .HasColumnType("int");

                    b.Property<float>("PricePerPerson")
                        .HasColumnType("real");

                    b.Property<float>("PricePerTruck")
                        .HasColumnType("real");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TruckAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RouteStopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RouteStopId")
                        .IsUnique()
                        .HasFilter("[RouteStopId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Dia")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TruckId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TruckId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.RouteStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteStops");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.SavedLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("SavedLocations");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Moment")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TruckId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("TruckId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Truck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastItv")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextItv")
                        .HasColumnType("datetime2");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surnames")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Company", b =>
                {
                    b.HasOne("PlusTrack.API.Domain.Entities.License", "License")
                        .WithOne("Company")
                        .HasForeignKey("PlusTrack.API.Domain.Entities.Company", "LicenseId");

                    b.Navigation("License");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Employee", b =>
                {
                    b.HasOne("PlusTrack.API.Domain.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Package", b =>
                {
                    b.HasOne("PlusTrack.API.Domain.Entities.RouteStop", "RouteStop")
                        .WithOne("Package")
                        .HasForeignKey("PlusTrack.API.Domain.Entities.Package", "RouteStopId");

                    b.HasOne("PlusTrack.API.Domain.Entities.User", null)
                        .WithMany("Packages")
                        .HasForeignKey("UserId");

                    b.Navigation("RouteStop");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Route", b =>
                {
                    b.HasOne("PlusTrack.API.Domain.Entities.Employee", "Employee")
                        .WithMany("Routes")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("PlusTrack.API.Domain.Entities.Truck", "Truck")
                        .WithMany("Routes")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.RouteStop", b =>
                {
                    b.HasOne("PlusTrack.API.Domain.Entities.Location", "Location")
                        .WithMany("RouteStops")
                        .HasForeignKey("LocationId");

                    b.HasOne("PlusTrack.API.Domain.Entities.Route", "Route")
                        .WithMany("RouteStops")
                        .HasForeignKey("RouteId");

                    b.Navigation("Location");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.SavedLocation", b =>
                {
                    b.HasOne("PlusTrack.API.Domain.Entities.Location", "Location")
                        .WithMany("SavedLocations")
                        .HasForeignKey("LocationId");

                    b.HasOne("PlusTrack.API.Domain.Entities.User", "User")
                        .WithMany("SavedLocations")
                        .HasForeignKey("UserId");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Track", b =>
                {
                    b.HasOne("PlusTrack.API.Domain.Entities.Location", "Location")
                        .WithMany("Tracks")
                        .HasForeignKey("LocationId");

                    b.HasOne("PlusTrack.API.Domain.Entities.Truck", "Truck")
                        .WithMany("Tracks")
                        .HasForeignKey("TruckId");

                    b.Navigation("Location");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Truck", b =>
                {
                    b.HasOne("PlusTrack.API.Domain.Entities.Company", "Company")
                        .WithMany("Trucks")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Company", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Trucks");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.License", b =>
                {
                    b.Navigation("Company");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Location", b =>
                {
                    b.Navigation("RouteStops");

                    b.Navigation("SavedLocations");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Route", b =>
                {
                    b.Navigation("RouteStops");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.RouteStop", b =>
                {
                    b.Navigation("Package");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.Truck", b =>
                {
                    b.Navigation("Routes");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("PlusTrack.API.Domain.Entities.User", b =>
                {
                    b.Navigation("Packages");

                    b.Navigation("SavedLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
